### ISSUE TITLE
Page Data Read (13h) - MGOS_VFS_DEV_ERR_CORRUPT 

### ISSUE THREAD

**Issue by HaToan** [mongoose-os-libs/vfs-dev-w25xxx#2]
I have problem read chip flash W25N01GVxxIG.
When I read flash "Page Data Read (13h) ". I alway was error: CORRUPT.
Help me. to solution this problem.
Thank you!

**Comment by rojer** [comment]
CORRUPT means ECC mimatch. this chip must be written in 2K pages, if you try to update in smaller chunks ECC will get computed wrong.

**Comment by rojer** [comment]
rather than using the device directly, i recommend you put LFS filesystem on it - see http://github.com/mongoose-os-libs/vfs-fs-lfs and http://github.com/mongoose-os-libs/fstab

**Comment by HaToan** [comment]
I reading a content of chip flash winbond W25N01GVxxIG. But when I load page by command "Page Data Read (13h)" after check status REG have flag ECC_0 and ECC_1 = 1 isn't the data integrity.

How to read 2K byte chip flash and data is integrity.

**Comment by rojer** [comment]
sorry, i don't have time for this. read the chip's datasheet or use filesystem as i suggested, it handles this. for you
